---
title: "Home"
author: ''
date: '2022-05-27'
slug: home
categories: []
tags: tags
description: Desc
hacker_news_id: ''
lobsters_id: ''
meta_img: /images/image.jpg
---

[[[insert a pic of myself or family here]]]

### Welcome fellow data nerds, current and prospective.  

My name is Saffron H. Evergreen (pronouns: they/she) and I am a graduate student in the MPH Biostatistics program at OHSU-PSU. I received my B.S. in Public Health: Health Services Administration in 2021 through the School of Public Health at OHSU-PSU.   
While building my skills and data analysis portfolio, I prefer to dive into research pertaining to rare genetic disorders, connective tissue disorders, autoimmune disorders, neurodiversity, disability rights, the history of eugenics, the industrial prison system and -to prevent severe burnout- I like to attempt fun data projects (i.e., “Did Death/Black Metal Really Impact the Spread of the Satanic Panic in the 80’s and 90’s?”… stay tuned).   


Currently, I am a student, a mom to 1 child and 2 dogs, a partner and trying to navigate academia and the workforce as a disabled person with a disabled family.   

Outside of work-school-things, I like to go to the beach, hike… “hike”, forage forest wreaths and/or bouquets, watch horror movies and documentaries, do stick n poke tattoos and go thrifting.  


Find me at [[_insert linkedin and github stuff here_]].  
(This will happen eventually)


