---
title: Background
author: Saffron Evergreen
date: '2022-05-27'
output: html_document
---



### How my relationship with biostatistics developed

#### *Physics, not classical*

It started in 10th grade when I became obsessed with quantum physics. Only to the extent that I loved how hard it made my brain work and how my mind was constantly blown. So long story short there was/is like no money, job growth or security in theoretical/astro/experimental/quantum physics.

#### *My love of research*

I moved to Portland for the Social Work program at PSU, then realized it wasn't aligning to my stress capabilities. So I took it up a notch and transferred to the pre-med Naturopathic Medicine program and felt *really* out of place. Then I reflected on what part of "doctor" I wanted, which was to work in research, policy, and anything more so behind the scenes.

#### *The Shrek to my Fiona*

Well my adviser was pretty blunt and told me getting a PhD is essentially not fitting for me. Not in a bad way, but I (was) a single mom with a high-needs child, dealing with health issues myself, and so on and so forth so she introduced me to the word ***b i o s t a t i s t i c s*** and it was like I had found my career-soulmate.

Due to my mystery diagnosis and being in year 3 of a highly-politicized and polarizing pandemic, I've grown even more interested in clinical research and have gotten over my fear of epidemiology.

#### *What is fueling my brain at the moment \~*

-   *clinical research: research transparency, accessibility, readability*
-   *(epi)genetics, anti-eugenics, rare disorders, autoimmune diseases, connective tissue diseases*
-   *neurodiversity, gender, sexuality, social dynamics*
-   *learning more about the accuracy on the things we rely too much on (labs, imaging, etc)*
-   *fungus, bacteria, deep-sea life, plant communication*
-   *and horror movies*

I would like to dedicate my remaining brainpower and ever-growing passion to the creators of [Bookdown](https://bookdown.org/), *probably the best free resource ever*.