---
title: About
author: Saffron Evergreen
date: '2022-05-27'
output: html_document
---


## A timeline on my love of science, math, and things I don't understand   


**1. Physics, a hobby?**   

It started in 10th grade when I became obsessed with quantum physics. Only to the extent that I loved how hard it made my brain work and how my mind was constantly blown. So long story short there was/is like no money, job growth or security in theoretical/astro/experimental/quantum physics.  

**2. My love of research**  

I moved to Portland for the Social Work program at PSU, then realized it wasn’t aligning to my stress capabilities. So I took it up a notch and transferred to the pre-med Naturopathic Medicine program and felt really out of place. Then I reflected on what part of “doctor” I wanted, which was to work in research, policy, and anything more so behind the scenes.  

**The Shrek to my Fiona**  

Well my adviser was pretty blunt and told me getting a PhD is essentially not fitting for me. Not in a bad way, but I (was) a single mom with a high-needs child, dealing with health issues myself, and so on and so forth so she introduced me to the word **_b i o s t a t i s t i c s_** and it was like I had found my career-soulmate.   




I would like to dedicate my remaining brainpower and ever-growing passion to the creators of [Bookdown](https://bookdown.org/), probably the best free resource ever.  
